[dev]
  command = "yarn live" # Command to start your dev server

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "14.15.1"

# [[headers]]
#   for = "*.jpg"
#   [headers.values]
#     Cache-Control = "public, max-age=31536000"

# [[headers]]
#   for = "*.png"
#   [headers.values]
#     Cache-Control = "public, max-age=31536000"

PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="true"
YARN_VERSION="2.3.3"